spring:
  application:
    name: notification-app
  jackson:
    visibility:
      field: non_private
    property-naming-strategy: SNAKE_CASE

  cloud:
    function:
      definition: receiveWorkFlowEvent;receiveExpired
    stream:
      bindings:
        receiveWorkFlowEvent-in-0:
          destination: work-flow-topic
          group: event
        receiveExpired-in-0:
          destination: expired-topic
          group: event
  main:
    web-application-type: none
  rabbitmq:
    connection-timeout: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

  level:
    root: info
    notification:
      infrastructure.datasource: DEBUG
